import jsPDF from "jspdf";
import type { AnalysisResult } from "@/types/analysis";
import { ROBOTO_REGULAR_BASE64, ROBOTO_BOLD_BASE64 } from "@/lib/pdf-fonts";
import {
  localeDateTag,
  translate,
  translateParams,
  type Locale,
} from "@/lib/i18n/dictionaries";
import { localizedPersonaDisplayName } from "@/lib/i18n/persona-labels";

function registerFonts(doc: jsPDF) {
  doc.addFileToVFS("Roboto-Regular.ttf", ROBOTO_REGULAR_BASE64);
  doc.addFont("Roboto-Regular.ttf", "Roboto", "normal");

  doc.addFileToVFS("Roboto-Bold.ttf", ROBOTO_BOLD_BASE64);
  doc.addFont("Roboto-Bold.ttf", "Roboto", "bold");

  doc.setFont("Roboto", "normal");
}

const COLORS = {
  primary: [12, 18, 34] as const, // lab-ink
  primaryDark: [15, 118, 110] as const, // brand-700
  primaryLight: [240, 253, 250] as const, // brand-50
  text: [12, 18, 34] as const,
  muted: [100, 116, 139] as const,
  border: [226, 232, 240] as const,
  cardBg: [244, 247, 250] as const, // lab-chalk
  white: [255, 255, 255] as const,
  success: [16, 185, 129] as const,
  warning: [245, 158, 11] as const,
  danger: [239, 68, 68] as const,
  signal: [200, 245, 66] as const,
};

const PAGE = {
  width: 210,
  height: 297,
  marginX: 15,
  contentWidth: 180,
  headerHeight: 32,
  bottom: 22,
  contentTop: 44,
};

function setText(doc: jsPDF, color: readonly number[]) {
  doc.setTextColor(color[0], color[1], color[2]);
}

function setFill(doc: jsPDF, color: readonly number[]) {
  doc.setFillColor(color[0], color[1], color[2]);
}

function setDraw(doc: jsPDF, color: readonly number[]) {
  doc.setDrawColor(color[0], color[1], color[2]);
}

function drawHeader(doc: jsPDF) {
  setFill(doc, COLORS.primary);
  doc.rect(0, 0, PAGE.width, PAGE.headerHeight, "F");

  setFill(doc, COLORS.white);
  doc.roundedRect(PAGE.marginX, 8, 16, 16, 3, 3, "F");
  setText(doc, COLORS.primary);
  doc.setFont("Roboto", "bold");
  doc.setFontSize(11);
  doc.text("FC", PAGE.marginX + 8, 18, { align: "center" });

  setText(doc, COLORS.white);
  doc.setFont("Roboto", "bold");
  doc.setFontSize(18);
  doc.text("FirstClick", PAGE.marginX + 22, 16);

  doc.setFont("Roboto", "normal");
  doc.setFontSize(9);
  doc.text("AI Product Validation Report", PAGE.marginX + 22, 23);

  setText(doc, COLORS.text);
}

function drawFooters(doc: jsPDF, locale: Locale) {
  const totalPages = doc.getNumberOfPages();
  const today = new Date().toLocaleDateString(localeDateTag(locale));

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    setDraw(doc, COLORS.border);
    doc.line(PAGE.marginX, PAGE.height - PAGE.bottom, PAGE.width - PAGE.marginX, PAGE.height - PAGE.bottom);

    doc.setFont("Roboto", "normal");
    doc.setFontSize(8.5);
    setText(doc, COLORS.muted);

    doc.text(`Generated: ${today}`, PAGE.marginX, PAGE.height - 14);
    doc.text("Generated by FirstClick AI", PAGE.width / 2, PAGE.height - 14, { align: "center" });
    doc.text(`Page ${i} / ${totalPages}`, PAGE.width - PAGE.marginX, PAGE.height - 14, { align: "right" });

    setText(doc, COLORS.text);
  }
}

function ensureSpace(doc: jsPDF, y: number, required: number): number {
  if (y + required > PAGE.height - PAGE.bottom - 6) {
    doc.addPage();
    drawHeader(doc);
    return PAGE.contentTop;
  }
  return y;
}

function sectionTitle(doc: jsPDF, title: string, y: number): number {
  y = ensureSpace(doc, y, 16);

  setFill(doc, COLORS.primary);
  doc.roundedRect(PAGE.marginX, y - 6, PAGE.contentWidth, 10, 2, 2, "F");

  setText(doc, COLORS.white);
  doc.setFont("Roboto", "bold");
  doc.setFontSize(13);
  doc.text(title, PAGE.marginX + 5, y + 1);

  setText(doc, COLORS.text);
  return y + 14;
}

function scoreBar(doc: jsPDF, label: string, value: number, y: number, invert = false): number {
  y = ensureSpace(doc, y, 12);

  doc.setFont("Roboto", "bold");
  doc.setFontSize(10.5);
  setText(doc, COLORS.text);
  doc.text(label, PAGE.marginX, y);

  const barX = PAGE.marginX + 55;
  const barWidth = 95;
  const barHeight = 5;

  setDraw(doc, COLORS.border);
  setFill(doc, COLORS.primaryLight);
  doc.roundedRect(barX, y - 4, barWidth, barHeight, 1.5, 1.5, "FD");

  const effective = invert ? 100 - value : value;
  const clamped = Math.max(0, Math.min(effective, 100));

  let fillColor: readonly number[] = COLORS.success;
  if (clamped < 40) fillColor = COLORS.danger;
  else if (clamped < 70) fillColor = COLORS.warning;

  setFill(doc, fillColor);
  if (clamped > 0) {
    doc.roundedRect(barX, y - 4, (barWidth * clamped) / 100, barHeight, 1.5, 1.5, "F");
  }

  doc.setFont("Roboto", "bold");
  doc.setFontSize(10);
  setText(doc, COLORS.text);
  doc.text(`${value}/100`, barX + barWidth + 6, y);

  return y + 11;
}

function bulletList(doc: jsPDF, items: string[], y: number, numbered = false): number {
  doc.setFont("Roboto", "normal");
  doc.setFontSize(10.5);

  items.forEach((item, i) => {
    const lines = doc.splitTextToSize(item, PAGE.contentWidth - 14);
    y = ensureSpace(doc, y, lines.length * 5.5 + 4);

    if (numbered) {
      setFill(doc, COLORS.primary);
      doc.circle(PAGE.marginX + 2.5, y - 1.5, 3, "F");
      setText(doc, COLORS.white);
      doc.setFont("Roboto", "bold");
      doc.setFontSize(7.5);
      doc.text(String(i + 1), PAGE.marginX + 2.5, y - 0.2, { align: "center" });
    } else {
      setFill(doc, COLORS.primary);
      doc.circle(PAGE.marginX + 1.5, y - 1.8, 1.1, "F");
    }

    doc.setFont("Roboto", "normal");
    doc.setFontSize(10.5);
    setText(doc, COLORS.text);
    doc.text(lines, PAGE.marginX + 8, y);

    y += lines.length * 5.5 + 4;
  });

  return y;
}

function paragraph(doc: jsPDF, text: string, y: number): number {
  const lines = doc.splitTextToSize(text, PAGE.contentWidth - 10);
  y = ensureSpace(doc, y, lines.length * 5.5 + 6);

  doc.setFont("Roboto", "normal");
  doc.setFontSize(10.5);
  setText(doc, COLORS.text);
  doc.text(lines, PAGE.marginX + 3, y);

  return y + lines.length * 5.5 + 6;
}

function likelihoodColor(likelihood: string): readonly number[] {
  if (likelihood === "Yüksek" || likelihood === "High") return COLORS.success;
  if (likelihood === "Orta" || likelihood === "Medium") return COLORS.warning;
  return COLORS.danger;
}

function likelihoodDisplay(likelihood: string, locale: Locale): string {
  if (likelihood === "Yüksek" || likelihood === "High") return translate(locale, "pdf.likelihoodHigh");
  if (likelihood === "Orta" || likelihood === "Medium") return translate(locale, "pdf.likelihoodMedium");
  return translate(locale, "pdf.likelihoodLow");
}

function personaCard(
  doc: jsPDF,
  persona: AnalysisResult["personas"][number],
  y: number,
  locale: Locale
): number {
  const t = (key: string) => translate(locale, key);
  const fields: Array<{ label: string; value: string }> = [
    { label: t("pdf.firstImpression"), value: persona.firstImpression },
    { label: t("pdf.understood"), value: persona.understood },
    { label: t("pdf.confusion"), value: persona.confusion },
    { label: t("pdf.dropOffReason"), value: persona.dropOffReason },
    { label: t("pdf.suggestion"), value: persona.suggestion },
  ];

  const wrapped = fields.map((f) => ({
    label: f.label,
    lines: doc.splitTextToSize(f.value, PAGE.contentWidth - 16) as string[],
  }));

  const headerHeight = 12;
  const fieldsHeight = wrapped.reduce((sum, f) => sum + f.lines.length * 5 + 7, 0);
  const cardHeight = headerHeight + fieldsHeight + 6;

  y = ensureSpace(doc, y, Math.min(cardHeight, PAGE.height - PAGE.contentTop - PAGE.bottom));

  const cardTop = y - 6;
  setFill(doc, COLORS.cardBg);
  setDraw(doc, COLORS.border);
  doc.roundedRect(PAGE.marginX, cardTop, PAGE.contentWidth, cardHeight, 3, 3, "FD");

  doc.setFont("Roboto", "bold");
  doc.setFontSize(12.5);
  setText(doc, COLORS.primaryDark);
  doc.text(localizedPersonaDisplayName(t, persona.name), PAGE.marginX + 6, y + 1);

  const badgeColor = likelihoodColor(persona.likelihood);
  const badgeText = translateParams(locale, "pdf.likelihood", {
    value: likelihoodDisplay(persona.likelihood, locale),
  });
  doc.setFont("Roboto", "bold");
  doc.setFontSize(8.5);
  const badgeWidth = doc.getTextWidth(badgeText) + 8;
  const badgeX = PAGE.marginX + PAGE.contentWidth - badgeWidth - 4;
  setFill(doc, badgeColor);
  doc.roundedRect(badgeX, y - 5, badgeWidth, 7, 2, 2, "F");
  setText(doc, COLORS.white);
  doc.text(badgeText, badgeX + 4, y - 0.5);

  y += 10;

  wrapped.forEach((f) => {
    doc.setFont("Roboto", "bold");
    doc.setFontSize(8.5);
    setText(doc, COLORS.muted);
    doc.text(f.label.toUpperCase(), PAGE.marginX + 6, y);
    y += 4.5;

    doc.setFont("Roboto", "normal");
    doc.setFontSize(10);
    setText(doc, COLORS.text);
    doc.text(f.lines, PAGE.marginX + 6, y);
    y += f.lines.length * 5 + 2.5;
  });

  setText(doc, COLORS.text);
  return y + 6;
}

export function generatePDF(
  result: AnalysisResult,
  productName?: string,
  source?: "openai" | "mock",
  extras?: {
    ragSources?: { citation: string; sourceType: string; excerpt: string }[];
    analysisId?: string | null;
    compareDelta?: { label: string; before: number; after: number; delta: number }[];
    locale?: Locale;
  }
) {
  const locale: Locale = extras?.locale === "en" ? "en" : "tr";
  const t = (key: string) => translate(locale, key);
  const doc = new jsPDF("p", "mm", "a4");
  registerFonts(doc);

  drawHeader(doc);

  let y = PAGE.contentTop;

  doc.setFont("Roboto", "bold");
  doc.setFontSize(16);
  setText(doc, COLORS.text);
  doc.text(productName || t("pdf.unknownProduct"), PAGE.marginX, y);
  y += 8;

  const today = new Date().toLocaleDateString(localeDateTag(locale));
  doc.setFont("Roboto", "normal");
  doc.setFontSize(10.5);
  setText(doc, COLORS.muted);
  doc.text(translateParams(locale, "pdf.date", { date: today }), PAGE.marginX, y);
  y += 6;
  doc.text(
    translateParams(locale, "pdf.source", {
      source: source === "openai" ? t("pdf.sourceAi") : t("pdf.sourceDemo"),
    }),
    PAGE.marginX,
    y
  );
  if (extras?.analysisId) {
    y += 6;
    doc.text(translateParams(locale, "pdf.analysisId", { id: extras.analysisId }), PAGE.marginX, y);
  }
  setText(doc, COLORS.text);
  y += 12;

  y = sectionTitle(doc, t("pdf.scores"), y);
  y = scoreBar(doc, t("pdf.overall"), result.overallScore, y);
  y = scoreBar(doc, t("pdf.clarity"), result.clarityScore, y);
  y = scoreBar(doc, t("pdf.adoption"), result.adoptionScore, y);
  y = scoreBar(doc, t("pdf.onboardingRisk"), result.onboardingRiskScore, y, true);
  y = scoreBar(doc, t("pdf.targetFit"), result.targetFitScore, y);
  y += 4;

  if (extras?.compareDelta && extras.compareDelta.length > 0) {
    y = sectionTitle(doc, t("pdf.compareDeltas"), y);
    const deltaLines = extras.compareDelta.map(
      (d) =>
        `${d.label}: ${d.before} → ${d.after} (${d.delta > 0 ? "+" : ""}${d.delta})`
    );
    y = bulletList(doc, deltaLines, y);
    y += 4;
  }

  y = sectionTitle(doc, t("pdf.personaSims"), y);
  result.personas.forEach((persona) => {
    y = personaCard(doc, persona, y, locale);
  });

  y = sectionTitle(doc, t("pdf.blindSpots"), y);
  y = bulletList(doc, result.blindSpots, y);
  y += 4;

  y = sectionTitle(doc, t("pdf.dropOffs"), y);
  y = bulletList(doc, result.dropOffPoints, y);
  y += 4;

  y = sectionTitle(doc, t("pdf.actionPlan"), y);
  y = bulletList(doc, result.actionPlan, y, true);
  y += 4;

  y = sectionTitle(doc, t("pdf.improvedPitch"), y);
  y = paragraph(doc, result.improvedPitch, y);
  y += 2;

  y = sectionTitle(doc, t("pdf.toughQuestions"), y);
  y = bulletList(doc, result.toughQuestions, y, true);

  if (extras?.ragSources && extras.ragSources.length > 0) {
    y += 4;
    y = sectionTitle(doc, t("pdf.sources"), y);
    const cites = extras.ragSources.map(
      (s) => `${s.citation} — ${s.excerpt.slice(0, 120)}${s.excerpt.length > 120 ? "…" : ""}`
    );
    y = bulletList(doc, cites, y);
  }

  drawFooters(doc, locale);

  const safeName = (productName || "FirstClick_Report").replace(/[^a-z0-9]+/gi, "_");
  doc.save(`${safeName}.pdf`);
}